apiVersion: v1
kind: ConfigMap
metadata:
  name: group-service-config
  namespace: default
data:
  SERVICE_SERVER_PORT: "9000"
  ZIPKIN_ENDPOINT: "http://localhost:9411/api/v2/spans"
  EUREKA_ENABLED: "false"
  DATABASE_URL: "jdbc:postgresql://localhost:5432/Messenger"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "25032001"
  STORAGE_SERVICE_URL: "http://localhost:6500"
  USER_SERVICE_URL: "http://localhost:7000"
  MESSAGING_SERVICE_URL: "http://localhost:1000"
  STORAGE_DIRECTORY: "GroupService/"
  SPRING_PROFILE: "localhost"

  