apiVersion: v1
kind: Pod
metadata:
  name: debezium-deploy.yaml
  labels:
    app: debezium-deploy.yaml
spec:
  containers:
    - name: debezium-deploy.yaml
      image: debezium/connect:1.4
      imagePullPolicy: IfNotPresent
      env:
        - name: BOOTSTRAP_SERVERS
          value: kafka-service:9092
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: connect_configs
        - name: OFFSET_STORAGE_TOPIC
          value: connect_offsets
        - name: KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://schema-registry-service:8081
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: http://schema-registry-service:8081
  restartPolicy: Always
  