apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 9092
      nodePort: 30173
      targetPort: 9092
  selector:
    app: kafka-broker