apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-enterprise-kafka:5.5.3
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "10.116.3.168:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.uid"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_JMX_PORT
              value: "9991"