apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    type: NodePort
    app: zookeeper
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181