---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:5.5.3
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"