---
namespace: default
images:
  - name: denpool/messenger-group-service
    newTag: "13"
  - name: denpool/messenger-lastseen-service
    newTag: "1"
  - name: denpool/messenger-profile-service
    newTag: "1"
  - name: denpool/messenger-storage-service
    newTag: "2"
resources:
  - ../../messenger/production/group-service
  - ../../messenger/production/lastseen-service
  - ../../messenger/production/profile-service
  - ../../messenger/production/storage-service