apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messenger
spec:
  destination:
    name: ''
    namespace: messenger-production
    server: 'https://kubernetes.default.svc'
  source:
    path: messenger
    repoURL: 'https://github.com/BestMessenger/Messenger-ArgoCD.git'
    targetRevision: main
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
