apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messenger
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: denpool/messenger-group-service:~v1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: messenger/production
    repoURL: 'https://github.com/BestMessenger/Messenger-ArgoCD.git'
    targetRevision: main
    directory:
      recurse: true
  sources: [ ]
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
