apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-service
  namespace: default
  labels:
    app: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  template:
    metadata:
      name: group-service
      labels:
        app: messenger
    spec:
      serviceAccountName: messenger-connector-db
      containers:
        - name: group-service
          image: denpool/messenger-group-service:0.0.1
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 9000
              path: /actuator/health/liveness
          envFrom:
            - secretRef:
                name: group-service-secret
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
