apiVersion: v1
kind: Service
metadata:
  name: group-service-service
  namespace: default
spec:
  selector:
    app: messenger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: NodePort
  