---
apiVersion: v1
kind: Service
metadata:
  name: group-service
  namespace: default
spec:
  selector:
    app: group-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
  