name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Number Test
        run: echo ${{ github.run_number }}



